language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - SAMP_SDK_ROOT=$TRAVIS_BUILD_DIR/sdk
  matrix:
    - STATIC=ON
    - STATIC=OFF

install:
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib cmake python-pip doxygen
  - sudo pip install ply cidl
  - git clone --depth 1 https://github.com/Zeex/samp-plugin-sdk.git sdk

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_C_COMPILER=${CC}
             -DCMAKE_CXX_COMPILER=${CXX}
             -DSAMPGDK_STATIC=${STATIC}
             -DSAMPGDK_BUILD_PLUGINS=ON
             -DSAMPGDK_BUILD_AMALGAMATION=ON

script:
  - make
  - make package

deploy:
  provider: releases
  api_key:
    secure: bATIOw3nSE2xY8PTnqAJT8lcR49myT0jTTrBco/Znb9GnWhUGjf7LAOV4DqC9sAdONNgVpzwx1qu0diaTaxpXV3VgByVQ64qJTSNYF2oQZgjO93nd1tkZ5rh+twVZNZtlScFnoN46bt1gf2aF/9oLq47adDXoUb+2HNMz3F/wIY=
  file_glob: true
  file:
    - 'sampgdk-*-linux.tar.gz'
    - 'sampgdk-*-amalgamation.zip'
  draft: true
  skip_cleanup: true
  on:
    repo: Zeex/sampgdk
    tags: true
    condition: "$CC = gcc"
